const STORE="masaAlSham_v1";
const WHATSAPP="9647772073950";
const countries=[
 {id:"syria",ar:"سوريا",en:"Syria",flag:"🇸🇾"},
 {id:"egypt",ar:"مصر",en:"Egypt",flag:"🇪🇬"},
 {id:"lebanon",ar:"لبنان",en:"Lebanon",flag:"🇱🇧"},
 {id:"turkey",ar:"تركيا",en:"Türkiye",flag:"🇹🇷"}
];
const statuses=[
 ["created","تم إنشاء الطلب","Request created"],
 ["review","قيد المراجعة","Under review"],
 ["accepted","تم قبول الحوالة","Transfer accepted"],
 ["processing","قيد التنفيذ","Processing"],
 ["sent","تم إرسال الحوالة","Transfer sent"],
 ["ready","جاهزة للاستلام","Ready for pickup"],
 ["completed","مكتملة","Completed"],
 ["cancelled","ملغاة","Cancelled"]
];
const defaultData={settings:{phone:"+9647772073950",whatsapp:"+9647772073950",companyAr:"ماسة الشام للحوالات المالية",companyEn:"Masa Al-Sham Financial Transfers"},rates:{},commissions:{},transfers:[]};
function load(){try{return JSON.parse(localStorage.getItem(STORE))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(d){localStorage.setItem(STORE,JSON.stringify(d))}
function money(n,c){return new Intl.NumberFormat(document.documentElement.lang==="en"?"en-US":"ar-IQ",{maximumFractionDigits:2}).format(n)+" "+c}
function countryName(id){const c=countries.find(x=>x.id===id);return c?c.ar:""}
function logo(){return `<svg viewBox="0 0 64 64" aria-label="ماسة الشام"><path d="M10 25 20 12h24l10 13-22 29z" fill="none" stroke="#caa24d" stroke-width="3"/><path d="m10 25 22 29 22-29M20 12l12 42 12-42M10 25h44" fill="none" stroke="#e4c875" stroke-width="1.5"/><path d="M4 32h12M48 32h12" stroke="#caa24d" stroke-width="2"/></svg>`}
function header(){return `<div class="topbar"><div class="container"><span>ماسة الشام للحوالات المالية · بغداد، العراق</span><span>الهاتف وWhatsApp: +9647772073950</span></div></div>
<nav class="nav"><div class="container navin"><a class="brand" href="#home">${logo()}<span>ماسة الشام<small>Masa Al-Sham Financial Transfers</small></span></a>
<div class="links"><a href="#home">الرئيسية</a><a href="#about">من نحن</a><a href="#services">خدماتنا</a><a href="#countries">الدول</a><a href="#calculator">حاسبة الحوالات</a><a href="#send">إرسال حوالة</a><a href="#track">تتبع حوالتي</a><a href="#faq">الأسئلة الشائعة</a><a href="#contact">تواصل معنا</a></div>
<div class="actions"><button class="lang" id="langBtn">English</button><a class="btn btn-primary" href="#send">إرسال حوالة</a><button class="iconbtn mobilemenu" onclick="alert('استخدم الروابط في الصفحة للتنقل بين الأقسام.')">☰</button></div></div></nav>`}
function footer(){return `<footer><div class="container footergrid"><div><div class="brand">${logo()}<span>ماسة الشام<small>Masa Al-Sham Financial Transfers</small></span></div><p>شركة حوالات مالية مقرها بغداد منذ 2020، تخدم التحويلات إلى سوريا ومصر ولبنان وتركيا.</p></div><div><h3>روابط</h3><a href="#about">من نحن</a><a href="#services">خدماتنا</a><a href="#countries">الدول</a><a href="#faq">الأسئلة الشائعة</a></div><div><h3>الخدمات</h3><a href="#calculator">حاسبة الحوالات</a><a href="#send">إرسال حوالة</a><a href="#track">تتبع حوالتي</a></div><div><h3>التواصل</h3><a href="tel:+9647772073950">+9647772073950</a><a href="https://wa.me/9647772073950" target="_blank" rel="noopener">WhatsApp</a><span>Baghdad, Iraq</span></div></div><div class="container copyright">© 2020–2026 Masa Al-Sham Financial Transfers. All rights reserved. · <a href="#privacy">سياسة الخصوصية</a> · <a href="#terms">الشروط والأحكام</a> · <a href="#fraud">سياسة مكافحة الاحتيال</a></div></footer>`}
function hero(){return `<section class="hero" id="home"><div class="container"><div><div class="eyebrow">من بغداد منذ 2020</div><h1>حوالاتك المالية… بثقة وأمان</h1><p>نوصّل أموالك من بغداد إلى سوريا ومصر ولبنان وتركيا، بخيارات استلام متعددة وخدمة واضحة تركز على الأمان وسهولة المتابعة.</p><div class="hero-actions"><a class="btn btn-gold" href="#send">إرسال حوالة</a><a class="btn btn-outline" href="#track">تتبع حوالتي</a><a class="btn btn-outline" href="https://wa.me/9647772073950" target="_blank">تواصل عبر WhatsApp</a></div></div><div class="network"><div class="node center">بغداد · العراق</div><div class="node a">🇸🇾 سوريا</div><div class="node b">🇪🇬 مصر</div><div class="node c">🇱🇧 لبنان</div><div class="node d">🇹🇷 تركيا</div></div></div></section>`}
function countriesSection(){return `<section class="section" id="countries"><div class="container"><div class="section-head"><div><h2>الدول التي نخدمها</h2><p class="muted">أربع وجهات فقط، كما هو محدد لخدمات الشركة حاليًا.</p></div></div><div class="grid4">${countries.map(c=>`<div class="card country-card"><div class="flag">${c.flag}</div><h3>${c.ar}</h3><p class="muted">${c.en}</p><p>خدمة طلب حوالة مع خيارات استلام نقدية أو محافظ إلكترونية أو حسابات بنكية بحسب المتاح.</p><button class="btn btn-primary" onclick="goSend('${c.id}')">إرسال حوالة</button></div>`).join("")}</div></div></section>`}
function services(){let arr=[["↔","الحوالات الدولية","طلب حوالات إلى سوريا ومصر ولبنان وتركيا."],["₿","الاستلام النقدي","استلام نقدي عبر الجهة أو الوكيل المعتمد عند توفره."],["◉","المحافظ الإلكترونية","إتاحة التحويل إلى محفظة إلكترونية عند توفرها."],["▣","الحسابات البنكية","إتاحة التحويل إلى حساب بنكي وفق البيانات المطلوبة."],["⌁","تتبع الحوالة","متابعة حالة الطلب باستخدام رقم الحوالة."],["▤","حاسبة الحوالات","عرض النتيجة وفق أسعار الصرف والعمولات التي يحددها المدير."]];return `<section class="section" id="services"><div class="container"><div class="section-head"><div><h2>خدماتنا</h2><p class="muted">أدوات واضحة لتسهيل طلب الحوالة ومتابعتها.</p></div></div><div class="grid3">${arr.map(x=>`<div class="card"><div class="service-icon">${x[0]}</div><h3>${x[1]}</h3><p class="muted">${x[2]}</p></div>`).join("")}</div></div></section>`}
function calculator(){return `<section class="section" id="calculator"><div class="container"><div class="section-head"><div><h2>حاسبة الحوالات</h2><p class="muted">الأسعار والعمولات لا تُفترض هنا؛ تظهر فقط بعد إعدادها من لوحة المدير.</p></div></div><div class="split"><div class="panel"><div class="formgrid"><div class="field"><label>الدولة</label><select id="calcCountry">${countries.map(c=>`<option value="${c.id}">${c.flag} ${c.ar}</option>`).join("")}</select></div><div class="field"><label>المبلغ</label><input id="calcAmount" type="number" min="0" step="0.01" placeholder="أدخل المبلغ"></div><div class="field"><label>العملة</label><select id="calcCurrency"><option value="IQD">IQD — دينار عراقي</option><option value="USD">USD — دولار أمريكي</option></select></div><div class="field"><label>طريقة الاستلام</label><select id="calcMethod"><option value="cash">نقدي</option><option value="wallet">محفظة إلكترونية</option><option value="bank">حساب بنكي</option></select></div></div></div><div class="panel"><h3>نتيجة الحاسبة</h3><div id="calcResult" class="empty">أدخل المبلغ واختر الدولة لعرض النتيجة بعد إعداد سعر الصرف والعمولة.</div><div class="notice" style="margin-top:14px">أسعار الصرف والعمولات قابلة للتغيير، ويُعتمد السعر النهائي عند تنفيذ الحوالة.</div></div></div></div></section>`}
function send(){return `<section class="section" id="send"><div class="container"><div class="section-head"><div><h2>إرسال حوالة</h2><p class="muted">هذا النموذج ينشئ طلبًا للمراجعة والتأكيد، ولا يعني تنفيذ التحويل تلقائيًا.</p></div></div><div class="panel"><div class="formgrid">
<div class="field"><label>اسم المرسل الكامل</label><input id="senderName" required></div><div class="field"><label>رقم هاتف المرسل</label><input id="senderPhone" required></div>
<div class="field"><label>المحافظة / المدينة</label><input id="senderCity"></div><div class="field"><label>طريقة التواصل</label><select id="contactMethod"><option>WhatsApp</option><option>هاتف</option></select></div>
<div class="field"><label>الدولة المستلمة</label><select id="sendCountry">${countries.map(c=>`<option value="${c.id}">${c.flag} ${c.ar}</option>`).join("")}</select></div>
<div class="field"><label>المبلغ</label><input id="sendAmount" type="number" min="0" step="0.01"></div>
<div class="field"><label>العملة</label><select id="sendCurrency"><option value="IQD">IQD — دينار عراقي</option><option value="USD">USD — دولار أمريكي</option></select></div>
<div class="field"><label>طريقة الاستلام</label><select id="sendMethod"><option value="cash">استلام نقدي</option><option value="wallet">محفظة إلكترونية</option><option value="bank">حساب بنكي</option></select></div>
<div class="field"><label>اسم المستفيد الكامل</label><input id="receiverName"></div><div class="field"><label>رقم هاتف المستفيد</label><input id="receiverPhone"></div>
<div class="field"><label>مدينة المستفيد</label><input id="receiverCity"></div><div class="field" id="walletNameField"><label>اسم المحفظة</label><input id="walletName"></div>
<div class="field" id="walletNumberField"><label>رقم المحفظة / الهاتف</label><input id="walletNumber"></div>
<div class="field" id="bankNameField"><label>اسم البنك</label><input id="bankName"></div><div class="field" id="accountNameField"><label>اسم صاحب الحساب</label><input id="accountName"></div>
<div class="field" id="accountNumberField"><label>رقم الحساب</label><input id="accountNumber"></div><div class="field" id="ibanField"><label>IBAN إن وجد</label><input id="iban"></div>
<div class="field full" id="swiftField"><label>SWIFT إن كان مطلوبًا</label><input id="swift"></div>
<div class="field full"><label>ملاحظات</label><textarea id="notes" rows="4"></textarea></div>
<div class="field full"><label><input type="checkbox" id="agree"> أقر بأن البيانات المدخلة صحيحة وأن الطلب يخضع لمراجعة وتأكيد الشركة.</label></div>
<div class="field full"><button class="btn btn-primary" onclick="createTransfer()">مراجعة وإنشاء الطلب</button></div>
</div></div></div></section>`}
function track(){return `<section class="section" id="track"><div class="container"><div class="section-head"><div><h2>تتبع حوالتي</h2><p class="muted">أدخل رقم الطلب الذي حصلت عليه بعد إنشاء الحوالة.</p></div></div><div class="panel"><div class="formgrid"><div class="field"><label>رقم الحوالة</label><input id="trackId" placeholder="MS-XXXXXXXX"></div><div class="field" style="align-self:end"><button class="btn btn-primary" onclick="trackTransfer()">تتبع</button></div></div><div id="trackResult" style="margin-top:22px"></div></div></div></section>`}
function about(){return `<section class="section" id="about"><div class="container"><div class="split"><div><div class="eyebrow" style="color:var(--gold)">من نحن</div><h2>ماسة الشام للحوالات المالية</h2><p>تأسست ماسة الشام للحوالات المالية عام 2020 في بغداد بهدف تقديم خدمات حوالات مالية سهلة وموثوقة للعملاء الذين يحتاجون إلى إرسال الأموال إلى سوريا ومصر ولبنان وتركيا.</p><p>نركز على وضوح خطوات الطلب، تعدد خيارات الاستلام المتاحة، خدمة العملاء، وإتاحة متابعة حالة الحوالة. طلب الحوالة عبر الموقع هو طلب للمراجعة والتأكيد، ويخضع التنفيذ النهائي لإجراءات الشركة.</p></div><div class="card"><h3>لماذا ماسة الشام؟</h3><p>✓ خبرة منذ 2020</p><p>✓ مكتب فعلي في بغداد</p><p>✓ شركة مرخصة</p><p>✓ خيارات استلام متعددة</p><p>✓ متابعة حالة الحوالة</p><p>✓ دعم مباشر عبر WhatsApp</p><p>✓ أسعار صرف وعمولات قابلة للتحديث</p></div></div></div></section>`}
function faq(){let q=[["كيف أرسل حوالة؟","اختر الدولة، استخدم الحاسبة عند الحاجة، ثم املأ نموذج إرسال الحوالة وراجع البيانات وأنشئ الطلب. بعد ذلك يمكنك إرساله إلى WhatsApp للمراجعة."],["ما الدول التي يمكن التحويل إليها؟","سوريا ومصر ولبنان وتركيا فقط وفق نطاق الخدمة المحدد حاليًا."],["ما طرق استلام الحوالة؟","يمكن أن تتوفر خدمة الاستلام النقدي أو المحفظة الإلكترونية أو الحساب البنكي بحسب الدولة والخيار المتاح عند تنفيذ الحوالة."],["كيف أعرف سعر الصرف؟","تظهر الحاسبة سعر الصرف والعمولة بعد أن يتم إعدادهما من لوحة المدير. لا يتم افتراض أسعار حقيقية داخل الموقع."],["هل يمكن تتبع الحوالة؟","نعم، استخدم رقم الطلب في صفحة تتبع حوالتي لمشاهدة الحالة المسجلة في النظام."],["كم يستغرق تنفيذ الحوالة؟","تختلف المدة حسب الدولة وطريقة الاستلام وإجراءات المراجعة، ويتم توضيح التفاصيل عند تأكيد الطلب."],["ماذا أفعل إذا أدخلت بيانات خاطئة؟","لا تعتمد الطلب قبل مراجعته. تواصل مع الشركة عبر WhatsApp أو الهاتف واذكر رقم الطلب إذا تم إنشاؤه."]];return `<section class="section" id="faq"><div class="container"><h2>الأسئلة الشائعة</h2><div class="faq" style="margin-top:22px">${q.map(x=>`<details><summary>${x[0]}</summary><p class="muted">${x[1]}</p></details>`).join("")}</div></div></section>`}
function legal(type){const data={privacy:["سياسة الخصوصية","نستخدم البيانات التي يدخلها العميل لغرض استقبال طلب الحوالة والتواصل بشأنه. لا ينبغي إدخال كلمات المرور أو رموز OTP أو أي بيانات دخول. الوصول إلى بيانات الطلبات يجب أن يكون مقيدًا بالجهات المخولة."],terms:["الشروط والأحكام","إنشاء الطلب عبر الموقع لا يعني تنفيذ الحوالة تلقائيًا. يخضع التنفيذ للمراجعة والتأكيد وإجراءات الشركة. يجب على العميل تقديم بيانات صحيحة وعدم استخدام الخدمة لأي نشاط غير قانوني."],fraud:["سياسة مكافحة الاحتيال","لا تشارك كلمات المرور أو رموز التحقق OTP أو بيانات الدخول مع أي شخص. ماسة الشام لا تطلب من العميل إدخال كلمة مرور أو OTP في نموذج الحوالة. عند الاشتباه بمحاولة احتيال، تواصل مباشرة عبر رقم الشركة الرسمي."]}[type];return `<section class="section"><div class="container"><div class="panel"><h2>${data[0]}</h2><p>${data[1]}</p></div></div></section>`}
function contact(){return `<section class="section" id="contact"><div class="container"><div class="cta"><div><h2>تواصل معنا</h2><p>ماسة الشام للحوالات المالية · Baghdad, Iraq · +9647772073950</p></div><div><a class="btn btn-gold" href="tel:+9647772073950">اتصال</a> <a class="btn btn-outline" href="https://wa.me/9647772073950" target="_blank">WhatsApp</a></div></div></div></section>`}
function render(){document.getElementById("app").innerHTML=header()+hero()+about()+countriesSection()+services()+calculator()+send()+track()+faq()+contact()+footer()+`<a class="whatsapp" href="https://wa.me/9647772073950" target="_blank">WhatsApp</a><div id="toast" class="toast"></div>`;bind()}
function bind(){document.getElementById("langBtn").onclick=()=>alert("النسخة الإنجليزية مهيأة ضمن المشروع ويمكن توسيع النصوص ثنائية اللغة في المرحلة الخلفية. العربية هي الواجهة الافتراضية.");["calcCountry","calcAmount","calcCurrency","calcMethod"].forEach(id=>document.getElementById(id).addEventListener("input",calc));document.getElementById("sendMethod").addEventListener("change",toggleMethodFields);toggleMethodFields();calc()}
function goSend(id){location.hash="send";setTimeout(()=>{document.getElementById("sendCountry").value=id},50)}
function toggleMethodFields(){const m=document.getElementById("sendMethod").value;["walletNameField","walletNumberField"].forEach(id=>document.getElementById(id).style.display=m==="wallet"?"grid":"none");["bankNameField","accountNameField","accountNumberField","ibanField","swiftField"].forEach(id=>document.getElementById(id).style.display=m==="bank"?"grid":"none")}
function calc(){const d=load(),c=document.getElementById("calcCountry").value,a=Number(document.getElementById("calcAmount").value||0),cur=document.getElementById("calcCurrency").value,m=document.getElementById("calcMethod").value;const key=`${c}_${cur}_${m}`,rate=Number(d.rates[key]||0),fee=Number(d.commissions[key]||0),out=document.getElementById("calcResult");if(!a||!rate){out.className="empty";out.textContent="لا توجد إعدادات سعر صرف وعمولة لهذه الخيارات حتى الآن. يمكن للمدير إضافتها من لوحة التحكم.";return}const commission=fee<1?fee*a:fee;const receive=Math.max(0,(a-commission)*rate);out.className="result";out.innerHTML=`<div class="resultrow"><span>سعر الصرف</span><strong>${rate}</strong></div><div class="resultrow"><span>العمولة</span><strong>${money(commission,cur)}</strong></div><div class="resultrow"><span>المبلغ المتوقع استلامه</span><strong class="bigresult">${receive.toLocaleString()} ${countryName(c)}</strong></div>`}
function createTransfer(){const d=load(),v=id=>document.getElementById(id).value.trim(),agree=document.getElementById("agree").checked;if(!agree){toast("يرجى تأكيد صحة البيانات قبل إنشاء الطلب.");return}if(!v("senderName")||!v("senderPhone")||!v("sendCountry")||!Number(v("sendAmount"))||!v("receiverName")){toast("يرجى إكمال الحقول الأساسية.");return}const id="MS-"+Date.now().toString(36).toUpperCase().slice(-8);const t={id,createdAt:new Date().toISOString(),sender:v("senderName"),senderPhone:v("senderPhone"),senderCity:v("senderCity"),country:v("sendCountry"),amount:Number(v("sendAmount")),currency:v("sendCurrency"),method:v("sendMethod"),receiver:v("receiverName"),receiverPhone:v("receiverPhone"),receiverCity:v("receiverCity"),walletName:v("walletName"),walletNumber:v("walletNumber"),bankName:v("bankName"),accountName:v("accountName"),accountNumber:v("accountNumber"),iban:v("iban"),swift:v("swift"),notes:v("notes"),status:"created"};d.transfers.unshift(t);save(d);const text=`طلب حوالة جديد - ماسة الشام\\n\\nرقم الطلب: ${t.id}\\nاسم المرسل: ${t.sender}\\nرقم الهاتف: ${t.senderPhone}\\nالدولة: ${countryName(t.country)}\\nاسم المستفيد: ${t.receiver}\\nالمبلغ: ${t.amount} ${t.currency}\\nطريقة الاستلام: ${t.method}\\nمدينة المستفيد: ${t.receiverCity||"-"}\\nملاحظات: ${t.notes||"-"}\\n\\nهذا طلب للمراجعة والتأكيد.`;document.getElementById("trackId").value=id;window.open("https://wa.me/"+WHATSAPP+"?text="+encodeURIComponent(text),"_blank");toast("تم إنشاء الطلب: "+id);trackTransfer()}
function trackTransfer(){const id=document.getElementById("trackId").value.trim().toUpperCase(),d=load(),t=d.transfers.find(x=>x.id===id),out=document.getElementById("trackResult");if(!t){out.innerHTML='<div class="empty">لم يتم العثور على حوالة بهذا الرقم. يرجى التأكد من الرقم أو التواصل مع خدمة العملاء عبر WhatsApp.</div>';return}const idx=statuses.findIndex(s=>s[0]===t.status);out.innerHTML=`<div class="card"><h3>${t.id}</h3><p>الدولة: ${countryName(t.country)} · المبلغ: ${t.amount} ${t.currency}</p><div class="timeline">${statuses.map((s,i)=>`<div class="step ${i<idx?"done":i===idx?"active":""}"><div class="dot">${i<idx?"✓":i+1}</div><div><strong>${s[1]}</strong><div class="muted">${s[2]}</div></div></div>`).join("")}</div></div>`}
function toast(x){const t=document.getElementById("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}
render();
